### ISSUE TITLE
jvmquake should perform configured action on resourceExhausted

### ISSUE THREAD

**Issue by hashbrowncipher** [jolynch/jvmquake#2]
In the scenario where the JVM hits `resourceExhausted` _without_ first getting stuck in GC stalls, jvmquake will send a SIGKILL regardless of the configured action. I'm not sure how likely this is, but if the user is expecting a core dump from any OOM, they might be surprised not to get one in this case.

**Comment by jolynch** [comment]
My understanding is that it sends the configured signal first and then sends the kill. I believe there is even an integration test which tests this case: https://github.com/jolynch/jvmquake/blob/b5ac9ae953b16a4969793d15128f9797d439a6d9/tests/test_basic_ooms.py#L45-L75

I'm closing this, please re-open if you disagree :-)
